// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB99rAAIm2X5L5YoLajg5XEOgS4pMqD4ek',
    appId: '1:94678294821:web:705abf94ac8532cfbdfacc',
    messagingSenderId: '94678294821',
    projectId: 'zenify-60993',
    authDomain: 'zenify-60993.firebaseapp.com',
    storageBucket: 'zenify-60993.firebasestorage.app',
    measurementId: 'G-3XFPQLQ4JZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIu6O1PdRt5OVUziWU20rqhHq2lh-yPxo',
    appId: '1:94678294821:android:64744926df8e7f99bdfacc',
    messagingSenderId: '94678294821',
    projectId: 'zenify-60993',
    storageBucket: 'zenify-60993.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1r2TCHtXzU2o1NrUJxHKAjmkWDMKKKto',
    appId: '1:94678294821:ios:561e8799c58ae2efbdfacc',
    messagingSenderId: '94678294821',
    projectId: 'zenify-60993',
    storageBucket: 'zenify-60993.firebasestorage.app',
    iosBundleId: 'com.example.mainproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1r2TCHtXzU2o1NrUJxHKAjmkWDMKKKto',
    appId: '1:94678294821:ios:561e8799c58ae2efbdfacc',
    messagingSenderId: '94678294821',
    projectId: 'zenify-60993',
    storageBucket: 'zenify-60993.firebasestorage.app',
    iosBundleId: 'com.example.mainproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB99rAAIm2X5L5YoLajg5XEOgS4pMqD4ek',
    appId: '1:94678294821:web:f955d12aa6e48dfabdfacc',
    messagingSenderId: '94678294821',
    projectId: 'zenify-60993',
    authDomain: 'zenify-60993.firebaseapp.com',
    storageBucket: 'zenify-60993.firebasestorage.app',
    measurementId: 'G-J7WXPP9GVY',
  );
}
